# Generated by Django 2.1.5 on 2023-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('nombre', models.CharField(max_length=50)),
                ('dosis', models.IntegerField()),
                ('frecuencia', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
            ],
        ),
    ]
