# Generated by Django 2.1.5 on 2023-04-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
        ('procedimientos', '0001_initial'),
        ('diagnosticos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('antecedentes', models.CharField(max_length=400)),
                ('alergias', models.CharField(max_length=400)),
                ('consultas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consultas.Consulta')),
                ('diagnosticos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.Diagnostico')),
                ('medicamentos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicamentos.Medicamento')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
                ('procedimientos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedimientos.Procedimiento')),
            ],
        ),
    ]
