# Generated by Django 2.1.5 on 2023-04-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio', models.IntegerField()),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicos.Medico')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente')),
            ],
        ),
    ]
