# Generated by Django 2.1.5 on 2023-04-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('afiliacion', '0001_initial'),
        ('eps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliacion',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eps.Eps'),
        ),
        migrations.AddField(
            model_name='afiliacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente'),
        ),
    ]
