# Generated by Django 4.2.1 on 2023-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliacion', '0002_auto_20230413_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
