# Generated by Django 2.1.5 on 2023-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
                ('tipo_sangre', models.CharField(max_length=50)),
            ],
        ),
    ]
