# Generated by Django 3.0.4 on 2023-05-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0002_alter_ips_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ips',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
